### ISSUE TITLE
Blast Furnace melt Raw Copper cause ticking crash.

### ISSUE THREAD

**Issue by FelixAgairu** [Globox1997/EarlyStage#25]
### Minecraft Version

1.21.x

### Mod Loader Version

0.16.7

### Mod Version

1.1.1

### Describe the Issue

```
java.lang.IllegalArgumentException: Recipe does not contain slot 2
	at knot//net.earlystage.misc.ExtraBlastingRecipeInput.method_59984(ExtraBlastingRecipeInput.java:13)
	at knot//com.illusivesoulworks.polymorph.common.capability.RecipeCache.insert(RecipeCache.java:79)
	at knot//com.illusivesoulworks.polymorph.common.capability.RecipeCache.compute(RecipeCache.java:61)
	at knot//com.illusivesoulworks.polymorph.common.capability.RecipeCache.get(RecipeCache.java:43)
	at knot//com.illusivesoulworks.polymorph.common.capability.AbstractRecipeData.getRecipe(AbstractRecipeData.java:71)
	at knot//com.illusivesoulworks.polymorph.common.PolymorphRecipeManager.getRecipe(PolymorphRecipeManager.java:43)
	at knot//com.illusivesoulworks.polymorph.common.PolymorphRecipeManager.getBlockEntityRecipe(PolymorphRecipeManager.java:34)
	at knot//net.minecraft.class_1863.handler$ecb000$polymorph$getRecipe(class_1863.java:1054)
	at knot//net.minecraft.class_1863.method_59993(class_1863.java)
	at knot//net.minecraft.class_1863.method_8132(class_1863.java:81)
	at knot//net.minecraft.class_2609.handler$bei000$earlystage$getCookTimeMixin(class_2609.java:644)
	at knot//net.minecraft.class_2609.method_17029(class_2609.java)
	at knot//net.minecraft.class_2609.method_31651(class_2609.java:318)
	at knot//net.minecraft.class_2818$class_5563.mixinextras$bridge$tick$15(class_2818.java)
	at knot//com.bawnorton.neruina.handler.TickHandler.safelyTickBlockEntity(TickHandler.java:169)
	at knot//net.minecraft.class_2818$class_5563.wrapOperation$djh000$neruina$catchTickingBlockEntity$notTheCauseOfTickLag(class_2818.java:1816)
	at knot//net.minecraft.class_2818$class_5563.method_31703(class_2818.java:691)
	at knot//net.minecraft.class_2818$class_5564.method_31703(class_2818.java:745)
	at knot//net.minecraft.class_1937.method_18471(class_1937.java:488)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:413)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at knot//net.minecraft.class_3176.method_3813(class_3176.java:299)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

### latest.log

https://gist.github.com/FelixAgairu/a0167d8c7f4b35c4ed13f49a6a2b7ae8

### Do you use any other mods except the required ones?

Blasting Raw Metal Blocks into Blocks https://modrinth.com/mod/blasting-raw-metal-blocks-into-blocks

**Comment by Globox1997** [comment]
This was a polymorph incompat, fixed with [https://github.com/Globox1997/EarlyStage/commit/59fb3c0ab35e77cd3fafd3aec03d696d1614585e](https://github.com/Globox1997/EarlyStage/commit/59fb3c0ab35e77cd3fafd3aec03d696d1614585e)
